yuhuatai/yuhuatai/urls.py
from django.conf.urls import url
from django.contrib import admin
from piaowu import views as piaowu_views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import staticfiles

urlpatterns = [

    url(r'^index_register_person/', piaowu_views.index_register_person),
    url(r'^index_register_team/', piaowu_views.index_register_team),
    url(r'^index_search_person/', piaowu_views.index_search_person),
    url(r'^index_search_team/', piaowu_views.index_search_team),
    url(r'^register_person/', piaowu_views.register_person),
    url(r'^register_team/', piaowu_views.register_team),
    url(r'^search_person/', piaowu_views.search_person),
    url(r'^search_team/', piaowu_views.search_team),

    url(r'^index/$', piaowu_views.index),
    url(r'^register/$', piaowu_views.register),
    url(r'^$', piaowu_views.index),

    url(r'^wx/$', piaowu_views.wx),
    url(r'^wx_in/$', piaowu_views.wx_in),
    url(r'^register_wx/$', piaowu_views.register_wx),
    url(r'^search_wx/$', piaowu_views.search_wx),

    url(r'^admin/', admin.site.urls),
]
urlpatterns += staticfiles_urlpatterns()

yuhuatai/piaowu/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import django.utils.timezone as timezone

# Create your models here.

class WxUser(models.Model):
    openid = models.CharField(max_length=100)
    name = models.CharField(max_length=10, blank=True)
    card_id = models.CharField(max_length=18, blank=True)
    telephone_number = models.CharField(max_length=11, blank=True)
    user_uuid = models.CharField(max_length=36)
    subscribe_date = models.DateTimeField('预约日期',default = timezone.now)
    register_datetime = models.DateTimeField('保存日期',default = timezone.now)
    status = models.PositiveIntegerField('票务状态',default = 0) # 0:未使用;1:已使用;2:已过期;

    def __unicode__(self):
        # 在Python3中使用 def __str__(self):
        return self.openid

class YuhuataiPerson(models.Model):
    card_id = models.CharField(max_length=18,db_index=True)
    visit_date = models.DateField(default = None)
    people_number = models.IntegerField(default = None)
    user_uuid = models.CharField(max_length=36,primary_key=True)

    #register_datetime = models.DateTimeField('保存日期',default = timezone.now)

    def __unicode__(self):
        # 在Python3中使用 def __str__(self):
        return self.card_id

class YuhuataiTeam(models.Model):
    card_id = models.CharField(max_length=18,db_index=True)
    visit_date = models.DateField(default = None)
    people_number = models.IntegerField(default = None)
    user_uuid = models.CharField(max_length=36,primary_key=True)

    #register_datetime = models.DateTimeField('保存日期',default = timezone.now)

    def __unicode__(self):
        # 在Python3中使用 def __str__(self):
        return self.card_id
class YuhuataiBlacklist(models.Model):
    card_id = models.CharField(max_length=18, db_index=True, primary_key=True)

if __name__ == "__main__":
    #YuhuataiUser.objects.create(card_id=“220802199201014321”, telephone_number=“15212345678”,user_uuid="",register_date="")
    print "ok"

yuhuatai/piaowu/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
import register.register_user as ru
import register.register as rg
import search.search as sc
import os


from django.views.decorators.csrf import csrf_exempt
import urllib
# Create your views here.
import urllib2
import json
from piaowu.models import YuhuataiPerson
from piaowu.models import YuhuataiBlacklist
import collections
#example:
# url = "https://api.weixin.qq.com/cgi-bin/usr/info?access_token=%s&openid=%s&lang=zh_CN"
# #分别填你的access_token,openid
# req = urllib2.Request(url%('access_token','openid'))
# #content是json类型的返回值 
# content = urllib2.urlopen(req).read()
# result = json.loads(content)
# msg = result.get('key')

@csrf_exempt
def wx(request):
    redirect_para = {
        #'appid':'wx4b80856c56b3ffd9',
        'appid':'wx1f3fafdacfa38a4c',
        'redirect_uri':'http://111.231.93.28/wx_in/',
        'response_type':'code',
        'scope':'snsapi_base',
        'state':123,
        'connect_redirect':1,
        }
    params = urllib.urlencode(redirect_para)
    redirect_url = "https://open.weixin.qq.com/connect/oauth2/authorize?%s#wechat_redirect" % params
    # web wang ye shou quan jie kou
    #https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx520c15f417810387&redirect_uri=https%3A%2F%2Fchong.qq.com%2Fphp%2Findex.php%3Fd%3D%26c%3DwxAdapter%26m%3DmobileDeal%26showwxpaytitle%3D1%26vb2ctag%3D4_2030_5_1194_60&response_type=code&scope=snsapi_base&state=123#wechat_redirect'
    #return HttpResponseRedirect(redirect_url)
    print(redirect_url)
    return render(request,'redirect.html', {'redirect_url':redirect_url})

@csrf_exempt
def wx_in(request):
    if request.method =='GET':# wechat
        code = request.GET.get('code')
        state =  request.GET.get('state')
        #openid = get_openid(code)
        #token_interface = "https://api.weixin.qq.com/sns/oauth2/access_token?appid=wx1f3fafdacfa38a4c&secret=addb1018b7137807c41eb2e0f29bde77&code=%s&grant_type=authorization_code" % code
        #new = ru.new_user(openid)
        try:
            openid = request.session['openid']
            try:
                user = WxUser.objects.get(openid=openid)
                new = False
            except:
                new = True
            dicts = {'code':code, 'state':state, 'new':new}
        except:
            dicts = {'code':code, 'state':state, 'new':True}
        return render(request, 'register_wx.html', dicts)
    else:
        return render(request, 'register_wx.html', {})

@csrf_exempt
def register_wx(request):
    print(request.method)
    print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
    if request.method == "POST":
        card_id = request.POST.get('card_id')
        telephone_number = request.POST['telephone_number']
        code = request.POST['code']

        openid = get_openid(code)
        request.session['openid'] = openid
        print(openid)
        first_register = ru.register_user_wx(openid, card_id, telephone_number)

        qr_code = '/static/images/qr_' + openid + '.png'

        print("###################################")
        print(qr_code)
        return render(request, 'register_wx.html', {'qr_code': qr_code, "first_register": first_register, 'new':False})
    return render(request, 'register_wx.html', {})

@csrf_exempt
def search_wx(request): #for wechat
    try:
        openid = request.session['openid']
        user = WxUser.objects.get(openid=openid)
        card_id = user.card_id
        qr_code = '/static/images/qr_' + openid + '.png'
        return render(request, 'search_wx.html', {'qr_code':qr_code, 'notice':"hahaha"})
    except:
        return HttpResponse("no user")

@csrf_exempt
def index(request):
    return render(request,'register.html',{})


@csrf_exempt
def register(request):
    if request.method == 'POST':
        card_id = request.POST['card_id']
        telephone_number = request.POST['telephone_number']
        code = request.POST['code']
        openid = False
        first_register = ru.register_user(openid, card_id, telephone_number)

        qr_code = '/static/images/qr_' + card_id + '.png'
        return render(request, 'register.html', {'qr_code': qr_code, "first_register": first_register})
    return render(request, 'register.html', {})


@csrf_exempt
def get_openid(code):
    #token_interface = "https://api.weixin.qq.com/sns/oauth2/access_token?appid=wx4b80856c56b3ffd9&secret=3d83eb571b2da051761cf25f2fcc98c1&code=%s&grant_type=authorization_code" % code
    token_interface = "https://api.weixin.qq.com/sns/oauth2/access_token?appid=wx1f3fafdacfa38a4c&secret=addb1018b7137807c41eb2e0f29bde77&code=%s&grant_type=authorization_code" % code
    #info = method_get_api(token_interface)
    req = urllib2.Request(token_interface)
    res = urllib2.urlopen(req).read()
    info = json.loads(res)
    print(info)
    access_token = info.get('access_token')
    openid = info.get('openid')
    return openid

def index_register_person(request):
    return render(request,'register_person.html')
def index_register_team(request):
    return render(request,'register_team.html')
def index_search_person(request):
    return render(request,'search_person.html')
def index_search_team(request):
    return render(request,'search_team.html')
def register_person(request):
    name = request.POST['name']
    profession=request.POST['profession']
    card_id = request.POST['card_id']
    visit_date = request.POST['visit_date']
    if visit_date.startswith("<"):
        visit_date = request.POST['visit_date2']
    '''
    year = request.POST['YYYY']
    month = request.POST['MM']
    day = request.POST['DD']
    if len(month) == 1:
        month = "0"+month
    if len(day) == 1:
        day = "0"+day
    '''
    ret_msg=""
    blackperson = YuhuataiBlacklist.objects.filter(card_id=card_id)
    if len(list(blackperson)) != 0:
        ret_msg = "对不起，您的证件号已被加入黑名单，不能预约！"
    else:
        ret = rg.register_person(card_id, visit_date)
        if ret == True:
            ret_msg = "预约成功！您已预约"+visit_date+"参观雨花台，请于当日携本人身份证入场！"
        else:
            ret_msg = "对不起，您已预约过"+visit_date+"参观雨花台，每人每日仅能预约一次！"
    return render(request, 'register_person.html', {'ret_msg': ret_msg,'name':name,'profession':profession,'card_id':card_id,'visit_date':visit_date})
def register_team(request):
    card_id = request.POST['card_id']
    year = request.POST['YYYY']
    month = request.POST['MM']
    day = request.POST['DD']
    if len(month) == 1:
        month = "0" + month
    if len(day) == 1:
        day = "0" + day
    people_number = request.POST['people_number']
    ret = rg.register_team(card_id, year+"-"+month+"-"+day,people_number)
    ret_msg = "预约成功!"
    return render(request, 'register_team.html', {'ret_msg': ret_msg})
def search_person(request):
    card_id = request.POST['card_id']
    persons = sc.search_person(card_id)

    ret_res =  {}
    ret_persons = collections.OrderedDict()
    if len(persons) == 0:
        ret_res["您还没有预约!"]=""
    else:
        ret_res["身份证号"]="预约日期"
        for p in persons:
            ret_persons[p] = p.visit_date
    '''
    ret_msg = "您的二维码如下："
    qr_code = ""
    if ret == True:
        qr_code = '/static/images/persons/qr_' + card_id + '.png'
        return render(request, 'search_person.html', {'qr_code': qr_code, "ret_msg": ret_msg})
    ret_msg = "您还没有预约，请点击如下链接进行个人预约"
    register_link = "http://yuhuatai/register_person.html"
    '''
    return render(request, 'search_person.html', {'ret_res':ret_res, 'ret_persons': ret_persons,'card_id':card_id})

def search_team(request):
    card_id = request.POST['card_id']
    ret = sc.search_team(card_id)
    ret_msg = "您的二维码如下："
    if ret == True:
        qr_code = '/static/images/teams/qr_' + card_id + '.png'
        return render(request, 'search_team.html', {'qr_code': qr_code, "ret_msg": ret_msg})
    ret_msg = "您还没有预约，请点击如下链接进行团体预约"
    register_link = "http://yuhuatai/register_team.html"
    return render(request, 'search_team.html', {'register_link': register_link, "ret_msg": ret_msg})


    

yuhuatai/piaowu/templates/redirect.html
<!DOCTYPE html>
<html debug="true">
<script type="text/javascript">
function check(){
	var re_url = "http://111.231.93.28/wx_in/";
	var redirect_url = "https://open.weixin.qq.com/connect/oauth2/authorize?state=123&response_type=code&appid=wx1f3fafdacfa38a4c&scope=snsapi_base&redirect_uri="+encodeURIComponent(re_url)+"#wechat_redirect"
	window.location.href=redirect_url
}
</script>
<body onload="check()">
</body>

yuhuatai/piaowu/templates/register_person.html
<!DOCTYPE html>
<html>
<head>
		<meta charset="utf-8">
		<title>注册界面</title>
		<link rel="stylesheet" href="/static/css/reset.css" />
		<link rel="stylesheet" href="/static/css/common.css" />
		<link rel="stylesheet" href="/static/css/font-awesome.min.css" />

		<script type="text/javascript" src="/static/js/laydate.js"></script>
	</head>
	<body>
		<div class="wrap login_wrap">
			<div class="content">
				
				<div class="logo"></div>
				
				<div class="login_box">	
					
					<div class="login_form">
						<div class="login_title">
							雨花台入场预约
						</div>
						<form action="/register_person/" method="post" id="form1">
							{% csrf_token %}
							<div class="form_text_ipt">
								<input name="name" type="text" placeholder="姓名" value="{{ name }}">
							</div>
							<div class="ececk_warning"><span>姓名不能为空</span></div>
							<div class="form_text_ipt">
								<input name="profession" type="text" placeholder="职业" value="{{ profession }}">
							</div>
							<div class="ececk_warning"><span>职业不能为空</span></div>
							<div class="form_text_ipt">
								<input name="card_id" type="text" id="id_card_id" placeholder="身份证号" value="{{ card_id }}">
							</div>
							<div class="ececk_warning"><span>身份证号不能为空</span></div>
							<!--
							<div class="form_text_ipt">
								<input name="code" type="text" placeholder="日期">
							</div>
							<div class="ececk_warning"><span>日期不能为空</span></div>
							-->
							<div class="form_text_ipt">
									<div class="inline laydate-icon" id="hello3" name="visit_date_div"><input name="visit_date2" type="text" placeholder="预约日期" value="{{ visit_date }}"></div>
									<input style="display:none" name="visit_date" id="my_input">
							</div>

								{{ ret_msg }}

							<div class="form_btn">
								<button type="button" onclick="Submit()">预约</button>
							</div>
							<div class="form_reg_btn">
								<span>查询预约信息？</span><a href="/index_search_person/">马上查询</a>
							</div>
						</form>

					</div>
				</div>
			</div>
		</div>
		<script type="text/javascript" src="/static/js/jquery.min.js" ></script>
		<script type="text/javascript" src="/static/js/common.js"></script>
		<script type="text/javascript">
		function Submit(){
			var visit_date = document.getElementById('hello3').innerHTML;
			document.getElementById('my_input').value = document.getElementById('hello3').innerHTML;

            var val = document.getElementById("id_card_id").value;

                if(val.length != 18){
                    alert("请输入有效的身份证号！");
                    return ;
                }
			document.getElementById('form1').submit();
		}
!function(){
	laydate.skin('dahong');//切换皮肤，请查看skins下面皮肤库
	laydate({elem: '#demo'});//绑定元素
}();


//日期范围限定在昨天到明天
laydate({
    elem: '#hello3',
    min: laydate.now(0), //-1代表昨天，-2代表前天，以此类推
    max: laydate.now(+7) //+1代表明天，+2代表后天，以此类推
});

		</script>
	</body>
</html>

yuhuatai/piaowu/templates/register_team.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<meta charset="UTF-8">
<title>
    雨花台预约游览
</title>
<link href="/static/css/index.css" rel="stylesheet">
<script src="/static/js/index.js" type="text/javascript"></script>
<script language="JavaScript">
function YYYYMMDDstart(){
	MonHead = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];

	//先给年下拉框赋内容
	var y  = new Date().getFullYear();
	for (var i = (y-30); i < (y+30); i++) //以今年为准，前30年，后30年
		   document.reg_testdate.YYYY.options.add(new Option(" "+ i +" 年", i));

	//赋月份的下拉框
	for (var i = 1; i < 13; i++)
		   document.reg_testdate.MM.options.add(new Option(" " + i + " 月", i));

	document.reg_testdate.YYYY.value = y;
	document.reg_testdate.MM.value = new Date().getMonth() + 1;
	var n = MonHead[new Date().getMonth()];
	if (new Date().getMonth() ==1 && IsPinYear(YYYYvalue)) n++;
		writeDay(n); //赋日期下拉框Author:meizz
	document.reg_testdate.DD.value = new Date().getDate();
}
if(document.attachEvent)
	window.attachEvent("onload", YYYYMMDDstart);
else
window.addEventListener('load', YYYYMMDDstart, false);
function YYYYDD(str) //年发生变化时日期发生变化(主要是判断闰平年)
{
	var MMvalue = document.reg_testdate.MM.options[document.reg_testdate.MM.selectedIndex].value;
	if (MMvalue == ""){ var e = document.reg_testdate.DD; optionsClear(e); return;}
	var n = MonHead[MMvalue - 1];
	if (MMvalue ==2 && IsPinYear(str)) n++;
	writeDay(n)
}
function MMDD(str)   //月发生变化时日期联动
{
	var YYYYvalue = document.reg_testdate.YYYY.options[document.reg_testdate.YYYY.selectedIndex].value;
	if (YYYYvalue == ""){ var e = document.reg_testdate.DD; optionsClear(e); return;}
	var n = MonHead[str - 1];
	if (str ==2 && IsPinYear(YYYYvalue)) n++;
	writeDay(n)
}
function writeDay(n)   //据条件写日期的下拉框
{
	var e = document.reg_testdate.DD; optionsClear(e);
	for (var i=1; i<(n+1); i++)
	e.options.add(new Option(" "+ i + " 日", i));
}
function IsPinYear(year)//判断是否闰平年
{
	return(0 == year%4 && (year%100 !=0 || year%400 == 0));
}
function optionsClear(e)
{
	e.options.length = 1;
}
function toVaild(){
                var val = document.getElementById("id_card_id").value;
                var val2 = document.getElementById("id_people_number").value;
                if(val.length == 18){
                    var len = val2.length;
                    for(var i=0;i<len;i++){
                        if(val2.charAt(i)>"9" || val2.charAt(i)<"0"){
                            alert("请输入有效的参观人数！");
                            return false;
                        }
                    }
                    return true;
                }
                else{
                    alert("请输入有效的身份证号！");
                    return false;
                }
}
</script>
<body style="margin:0px">
<div style="background-color:red;height:60px;font-family:'Georgia';font-size:35px;color:white">雨花台入场预约</div>

<!--选项卡-->
    <div id="tab">
        <!--主要内容-->
        <div id="tab-content">
            <div class="dom" style="display: block;" id="dom1">
                <p>&nbsp&nbsp请输入如下信息进行团体预约:</p>
                <form name = "reg_testdate" action="/register_team/" method="post" onsubmit="return toVaild()">
                    {% csrf_token %}
                    &nbsp&nbsp领队姓名：&nbsp&nbsp&nbsp&nbsp&nbsp<input type="text" name="name" id="id_name">
                    <br>
                    &nbsp&nbsp领队职业：&nbsp&nbsp&nbsp&nbsp&nbsp<input type="text" name="profession" id="id_profession">
                    <br>
                    <font color="red">*</font>领队身份证号:<input type="text" name="card_id" id="id_card_id">
                    <br>
                    <font color="red">*</font>人数：&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<input type="text" name="people_number" id="id_people_number">
                    <br>
                    <font color="red">*</font>请选择日期：
                    <select name="YYYY" onChange="YYYYDD(this.value)">
		                <option value="">请选择 年</option>
	                </select>
                    <select name="MM" onChange="MMDD(this.value)">
                        <option value="">选择 月</option>
                    </select>
                    <select name="DD">
                        <option value="">选择 日</option>
                    </select>
                    <input type="submit" value="预约">
                </form>
                <table>
                    <tr>
                        <!--<img src = "/static/images/qr_123.png" ></img>-->
                         <!--   <img src = {{ qr_code }} ></img>-->
                        {{ ret_msg }}
                    </tr>
                </table>
                <p>{{ xx }}</p>
            </div>

        </div>
    </div>



</body>
</html>

yuhuatai/piaowu/templates/register_wx.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="zh-cmn-Hans">
<head>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">    
<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0,viewport-fit=cover">
<title>
    雨花台预约游览
</title>
<link href="/static/css/weui-1.1.2/dist/style/weui.min.css" rel="stylesheet">
<script src="/static/js/weui.min.js"></script>
<script src="/static/js/zepto.min.js"></script>
<!-- <script src="https://cdn.bootcss.com/jquery-weui/1.1.2/js/jquery-weui.min.js"></script> -->
<script type="text/javascript">
    function test_post(){
        alert("asdfadfa");
        var testform=document.getElementById("register");
        testform.submit();
    }
</script>
</head>

<body ontouchstart>
<div class="page">
    <div class="page__hd">
        <div class="page__title">雨花台入场预约</div>
    </div>
    <div class="page__bd">
            {% if new %}
            <div class="weui-cells__title">请输入预约信息</div>
                <form id="register" action="/register_wx/" method="post">
                    {% csrf_token %}
                    <div class="weui-cells weui-cells_form">
                    <div class="weui-cell">
                        <div class="weui-cell__hd"><label class="weui-label">身份证号码:</label></div>
                        <div class="weui-cell__bd">
                         <input type="text"  name="card_id" class="weui-input"  placeholder="请输入身份证号" />
                        </div>
                    </div>
                    <div class="weui-cell">
                         <div class="weui-cell__hd"><label class="weui-label">手机号:</label></div>
                        <div class="weui-cell__bd">
                         <input type="text" class="weui-input" placeholder="请输入手机号" name="telephone_number">
                         </div>
                    </div>
                    </div>
                    <div class="page__bd page__bd_spacing">
                        <a href="javascript:;" class="weui-btn weui-btn_default" id="showDatePicker">选择预约日期</a>
                        <input type="hidden" id="date" name="date" >
                    </div>
                    <div class="page_bd page__bd_spacing">
                        <input type="hidden" name="openid" value={{openid}}>
                        <input type="hidden" name="code" value={{code}}>
                        <!-- <input type="submit" class="weui-btn weui-btn_primary" value="注册"> -->
                    </div>
                    <a href="javascript:;" onclick="test_post()" class="weui-btn weui-btn_primary">预约</a>
                    <!-- <input type="submit" class="weui-btn weui-btn_primary" value="预约"> -->
                </form>
            {% else %}
            <div class="weui-cells__title">注册信息</div>
                <form action="/search_wx/" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="openid" value={{openid}}>
                    <input type="submit" class="weui-btn weui-btn_primary" value="获取入场二维码">
                </form>
                <table>
                    <tr>
                     <img src={{qr_code}}></img>
                    </tr>
                </table>
            {% endif %}
                
    </div>
</div>
<script type="text/javascript">
$('#showDatePicker').on('click', function () {
        weui.datePicker({
            start: 1990,
            end: new Date().getFullYear(),
            defaultValue: [new Date().getFullYear(), new Date().getMonth()+1, new Date().getDate()],
            onChange: function (result) {
                console.log(result);
            },
            onConfirm: function (result) {
                var expect_date=result[0]+ "年" + result[1]+ "月" + result[2]+"日";
                var input = document.getElementById("date");
                input.value = expect_date;
                //$(this).text(expect_date);
                document.getElementById("showDatePicker").innerText = expect_date;
                console.log(result);
            }
        });
});
</script>
   <!--  <script src="/static/js/zepto.min.js"></script>
    <script type="text/javascript" src="/static/js/jweixin-1.0.0.js"></script>
    <script src="/static/js/weui.min.js"></script>
    <script src="/static/js/example.js"></script> -->
</body>

</html>

yuhuatai/piaowu/templates/search_person.html
<!DOCTYPE html>
<html>
	
<head>
		<meta charset="utf-8">
		<title>登录界面</title>
		<style>
		.divcss5{
			width:130px;height:30px;
			/*border:1px solid #000;*/
			display:-moz-inline-box; /* css注释：for ff2 */
			display:inline-block;
			font-size:15px;
			text-align:center;
			padding:1px;
			}
		</style>
		<link rel="stylesheet" href="/static/css/reset.css" />
		<link rel="stylesheet" href="/static/css/common.css" />
		<link rel="stylesheet" href="/static/css/font-awesome.min.css" />
	</head>
	<body>
		<div class="wrap login_wrap">
			<div class="content">
				<div class="logo"></div>
				<div class="login_box">	
					
					<div class="login_form">
						<div class="login_title">
							雨花台预约信息查询
						</div>
						<form action="\search_person\" method="post" onsubmit="return toVaild()">
							{% csrf_token %}
							<div class="form_text_ipt">
								<input id="id_card_id" name="card_id" type="text" placeholder="身份证号" value="{{ card_id }}">
							</div>
							<div class="ececk_warning"><span>身份证号不能为空</span></div>
<!--
							<div class="form_text_ipt">
								<span class="divcss5">身份证号</span><span class="divcss5">预约日期</span>
							</div>-->
							<div class="form_text_ipt" style="height:auto">
								{% for key, value in ret_res.items %}
								<span class="divcss5" style="width:160px">{{ key }}</span><span class="divcss5">{{ value }}</span>
								{% endfor %}
							{% for key, value in ret_persons.items %}
								<span class="divcss5" style="width:160px">{{ key.card_id }}</span><span class="divcss5">{{ value|date:"Y-m-d" }}</span></br>
							{% endfor %}
							</div>
							<div class="form_btn">
								<button type="submit">查询</button>
							</div>
							<div class="form_reg_btn">
								<span>还没有预约？</span><a href="/index_register_person/">马上预约</a>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
		<script type="text/javascript" src="/static/js/jquery.min.js" ></script>
		<script type="text/javascript" src="/static/js/common.js" ></script>

		<script language="JavaScript">
		function toVaild(){
                var val = document.getElementById("id_card_id").value;
                if(val.length == 18){
                    return true;
                }
                alert("请输入有效的身份证号！");
                return false;
		}
		</script>
	</body>
</html>

yuhuatai/piaowu/templates/search_team.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<meta charset="UTF-8">
<title>
    雨花台预约游览
</title>
<link href="/static/css/index.css" rel="stylesheet">
<script src="/static/js/index.js" type="text/javascript"></script>
<script language="JavaScript">
function toVaild(){
                var val = document.getElementById("id_card_id").value;

                if(val.length == 18){
                    return true;
                }
                else{
                    alert("请输入有效的身份证号！");
                    return false;
                }
}
</script>
<body style="margin:0px">
<div style="background-color:red;height:60px;font-family:'Georgia';font-size:35px;color:white">雨花台入场查询</div>

<!--选项卡-->
    <div id="tab">
        <!--主要内容-->
        <div id="tab-content">
            <div class="dom" style="display: block;" id="dom1">
                <p>&nbsp&nbsp请输入领队人身份证号码进行查询:</p>
                <form name = "reg_testdate" action="/search_team/" method="post" onsubmit="return toVaild()">
                    {% csrf_token %}
                    &nbsp&nbsp身份证号码:&nbsp&nbsp&nbsp&nbsp<input type="text" name="card_id" id="id_card_id">

                    <input type="submit" value="查询">
                </form>
                <table>
                    <tr>
                        <!--<img src = "/static/images/qr_123.png" ></img>-->
                        <p>{{ ret_msg }}</p>
                        <p>{{ register_link }}</p>
                        <img src = {{ qr_code }} ></img>

                    </tr>
                </table>
                <p>{{ xx }}</p>
            </div>

        </div>
    </div>



</body>
</html>

yuhuatai/piaowu/templates/search_wx.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0,viewport-fit=cover">
<title>
    雨花台入场二维码查询
</title>
<link href="/static/css/weui-1.1.2/dist/style/weui.min.css" rel="stylesheet">
<script src="/static/js/index.js" type="text/javascript"></script>
</head>
<body style="margin:0px">
<div style="background-color:red;height:60px;font-family:'Georgia';font-size:35px;color:white">雨花台入场二维码查询</div>

<!--选项卡-->
    <div id="tab">
        <!--主要内容-->
        <div id="tab-content">
            <div class="dom" style="display: block;" id="dom1">
                <table>
                    <tr>
                        <!--<img src = "/static/images/qr_123.png" ></img>-->
                            <img src = {{ qr_code }} ></img>
                    </tr>
                </table>
                <p>{{ xx }}</p>
            </div>

        </div>
    </div>



</body>
</html>